"""
PDF export service.
Renders a SOAP dict to a styled clinical PDF using ReportLab.
ReportLab is pure Python — no system GTK/Pango libs needed (works on Windows).
"""

from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ── Colour palette ──────────────────────────────────────────────────────────
BLUE       = colors.HexColor("#1d4ed8")
LIGHT_GRAY = colors.HexColor("#f8fafc")
MID_GRAY   = colors.HexColor("#e2e8f0")
TEXT_DARK  = colors.HexColor("#0f172a")
TEXT_MUTED = colors.HexColor("#6b7280")
TEXT_FOOT  = colors.HexColor("#9ca3af")

# ── Paragraph styles ────────────────────────────────────────────────────────
_base = getSampleStyleSheet()["Normal"]

STYLE_TITLE = ParagraphStyle(
    "Title",
    parent=_base,
    fontSize=18,
    textColor=BLUE,
    fontName="Helvetica-Bold",
    spaceAfter=4,
)
STYLE_META = ParagraphStyle(
    "Meta",
    parent=_base,
    fontSize=9,
    textColor=TEXT_MUTED,
    spaceAfter=12,
)
STYLE_SECTION_LABEL = ParagraphStyle(
    "SectionLabel",
    parent=_base,
    fontSize=8,
    textColor=BLUE,
    fontName="Helvetica-Bold",
    spaceBefore=14,
    spaceAfter=4,
    textTransform="uppercase",
    letterSpacing=0.8,
)
STYLE_BODY = ParagraphStyle(
    "Body",
    parent=_base,
    fontSize=10,
    textColor=TEXT_DARK,
    leading=15,
    spaceAfter=4,
)
STYLE_FOOTER = ParagraphStyle(
    "Footer",
    parent=_base,
    fontSize=8,
    textColor=TEXT_FOOT,
    alignment=1,  # centred
)


def _section_block(label: str, content: str) -> list:
    """Return flowables for one SOAP section (label + shaded content box)."""
    content = content.strip() or "—"
    # Wrap in a single-cell table to get the shaded background + padding
    table = Table(
        [[Paragraph(content, STYLE_BODY)]],
        colWidths=[15.5 * cm],
    )
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
        ("BOX",        (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    return [
        Paragraph(label, STYLE_SECTION_LABEL),
        table,
    ]


def render_soap_pdf(soap: dict) -> bytes:
    """Render a SOAP dict to PDF bytes using ReportLab."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=3 * cm,
        rightMargin=3 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    patient_id   = soap.get("patient_id", "Unknown")

    story = [
        Paragraph("SOAP Note Summary", STYLE_TITLE),
        Paragraph(f"Patient ID: {patient_id} &nbsp; | &nbsp; Generated: {generated_at}", STYLE_META),
        HRFlowable(width="100%", thickness=1.5, color=BLUE, spaceAfter=6),
        Spacer(1, 4),
    ]

    for label, key in [
        ("Subjective",  "subjective"),
        ("Objective",   "objective"),
        ("Assessment",  "assessment"),
        ("Plan",        "plan"),
    ]:
        story.extend(_section_block(label, soap.get(key, "")))

    story += [
        Spacer(1, 20),
        HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=6),
        Paragraph(
            "Generated by ClinicalSOAP — AI-assisted documentation. "
            "Not a substitute for clinical judgment.",
            STYLE_FOOTER,
        ),
    ]

    doc.build(story)
    return buf.getvalue()